config/routes.rb
Spred::Application.routes.draw do
  resources :friends

  resources :trends

  resources :dashboards

  resources :entries

  resources :users

end

app/models/trend.rb
class Trend < ActiveRecord::Base
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  # GET /trends
  # GET /trends.json
  def index
    @trends = Trend.all
    @friendsphones = User.first.friends.map {|f| f.phone}
    @sickfriends = User.find_all_by_phone(@friendsphones)

    @allsickfriendentries = Array.new

    @weekago = Time.now - 1.week
    @sickfriends.each do |f|
      f.entries.each do |e|
       @allsickfriendentries << e if e.entrytime >= @weekago
      end
    end

    #@weekago = Time.now - 1.week
    #@relevantentries = Entry.find(:all, :conditions => ['entrytime >= ? and ', @weekago])
    #@union = @relevantentries | @sickfriends.entries


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trends }
    end
  end

  # GET /trends/1
  # GET /trends/1.json
  def show
    @trend = Trend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trend }
    end
  end

  # GET /trends/new
  # GET /trends/new.json
  def new
    @trend = Trend.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trend }
    end
  end

  # GET /trends/1/edit
  def edit
    @trend = Trend.find(params[:id])
  end

  # POST /trends
  # POST /trends.json
  def create
    @trend = Trend.new(params[:trend])

    respond_to do |format|
      if @trend.save
        format.html { redirect_to @trend, notice: 'Trend was successfully created.' }
        format.json { render json: @trend, status: :created, location: @trend }
      else
        format.html { render action: "new" }
        format.json { render json: @trend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trends/1
  # PUT /trends/1.json
  def update
    @trend = Trend.find(params[:id])

    respond_to do |format|
      if @trend.update_attributes(params[:trend])
        format.html { redirect_to @trend, notice: 'Trend was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @trend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trends/1
  # DELETE /trends/1.json
  def destroy
    @trend = Trend.find(params[:id])
    @trend.destroy

    respond_to do |format|
      format.html { redirect_to trends_url }
      format.json { head :ok }
    end
  end
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/views/trends/_form.html.erb
<%= form_for(@trend) do |f| %>
  <% if @trend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trend.errors.count, "error") %> prohibited this trend from being saved:</h2>

      <ul>
      <% @trend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trends/edit.html.erb
<h1>Editing trend</h1>

<%= render 'form' %>

<%= link_to 'Show', @trend %> |
<%= link_to 'Back', trends_path %>

app/views/trends/index.html.erb
<%=@allsickfriendentries.to_json(:only => [:user_id, :sickstatus, :entrytime])%>


<h1>Listing trends</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trends.each do |trend| %>
  <tr>
    <td><%= link_to 'Show', trend %></td>
    <td><%= link_to 'Edit', edit_trend_path(trend) %></td>
    <td><%= link_to 'Destroy', trend, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trend', new_trend_path %>

app/views/trends/new.html.erb
<h1>New trend</h1>

<%= render 'form' %>

<%= link_to 'Back', trends_path %>

app/views/trends/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_trend_path(@trend) %> |
<%= link_to 'Back', trends_path %>